config/routes.rb
Rails.application.routes.draw do
	root 'flights#index'
	resources :flights
	resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
	validates :code, presence: true
	has_many :departing_flights, class_name: "Flight", foreign_key: :from_airport_id
	has_many :arriving_flights, class_name: "Flight", foreign_key: :to_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :flight
	has_many :passengers
	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :to_airport,   class_name: "Airport"
	belongs_to :from_airport, class_name: "Airport"
	has_one    :booking


	validates :start_time,   presence: true
	validates :duration,     presence: true
	validates :to_airport,   presence: true
	validates :from_airport, presence: true

	def self.get_start_times
		Flight.find_by_sql("select distinct start_time from flights order by start_time asc")
	end

	def formatted_start_time
		start_time.strftime("%m/%d/%Y %I:%M %p")
	end

	def self.find_flights(search_params)
		from_airport_id = search_params["from_airport_id"].to_i
		to_airport_id   = search_params["to_airport_id"].to_i
		date = Flight.assemble_date(search_params["date(1i)"],
								  search_params["date(2i)"],
								  search_params["date(3i)"])
		low_bound  = date - 15.days
		high_bound = date + 15.days
		Flight.where("from_airport_id = ? AND to_airport_id = ?
			          AND start_time >= ? AND start_time <= ?",
			          from_airport_id, to_airport_id,
			          low_bound, high_bound)
	end

	def self.assemble_date(year,month,day)
		DateTime.new(year.to_i,month.to_i,day.to_i)
	end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def index
		@bookings = Booking.all
	end

	def new

		@booking = Booking.new
		@flight = Flight.find(params[:flight_id].to_s)
		#@passengers = []
		count = params[:num_tickets].to_i
		count.times do
			@booking.passengers.build
		end
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save
			redirect_to booking_path(@booking)
		end
	end

	def show
		@booking = Booking.find(params[:id])
		@flight = @booking.flight
	end

	private
		def booking_params
			params.require(:booking).permit(:flight_id,
				passengers_attributes: [:name, :email])
		end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@flight = Flight.new
		#@dates = Flight.get_start_times.format_date.uniq
		if params[:flight]
			@flights = Flight.find_flights(search_params)
		end
	end

	private

		def search_params
			params.require(:flight).permit(:from_airport_id,
										   :to_airport_id,
										   :num_tickets,
										   "date(1i)", "date(2i)",
										   "date(3i)")
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/index.html.erb
<ul>
  <% @bookings.each do |b| %>
  	<li><%= b.inspect %></li>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<p><%= params.inspect %></p>
<p><%= @booking.flight.inspect %></p>
<h2>Booking Info</h2>

<%= form_with(model: @booking, local: true) do |f| %>
  <%= f.hidden_field(:flight_id, value: @flight.id) %>
    <b>Votre Vol:</b>
    <br>
    ID de Vol: <%= @flight.id %>
    <br>
    Depart de: <%=  @flight.from_airport.code %>
	<br>
	Arrive a: <%= @flight.to_airport.code %>
	<br>
	Heure de depart: <%= @flight.formatted_start_time %>
	<br>
	<br>
  Passagers:
  <ul>
  	<%= f.fields_for :passengers do |p_form| %>
  	  <li>
  	  	<%= p_form.label :name %>
  	  	<%= p_form.text_field :name %>
  	  	<br>
  	  	<%= p_form.label :email %>
  	  	<%= p_form.text_field :email %>
  	  	<br>
  	  </li>
  	<% end %>
  </ul>
  <%= f.submit "reserver votre vol" %>
<% end %>

app/views/bookings/show.html.erb
<%= @booking.inspect %>
<h2>Votre Information de Booking</h2>
<h3>Information de Vol</h3>
Depart de: <%=  @flight.from_airport.code %>
<br>
Arrive a: <%= @flight.to_airport.code %>
<br>
Heure de depart: <%= @flight.formatted_start_time %>
<br>
Duree: <%= @flight.duration %>
<h3>Passagers</h3>
<% @booking.passengers.each do |p| %>
  <br>
  Nom: <%= p.name %>
  <br>
  E-Mail: <%= p.email %>
  <br>
<% end %>

app/views/flights/_search.html.erb
<h1>rechercher des vols</h1>

<%= form_with(model: @flight, url: flights_path, method: 'get', local: true) do |f| %>
  <%= f.label :from_airport_id, "Au depart de: " %>
  <%= f.collection_select :from_airport_id, Airport.all, :id, :code %>
  <br>
  <%= f.label :to_airport_id, "Arrivee a: " %>
  <%= f.collection_select :to_airport_id, Airport.all, :id, :code %>
  <br>
  <%= f.label :num_tickets, "Combien de Passagers? " %>
  <%= f.select :num_tickets, options_for_select([[1,1],[2,2],
  											   [3,3],[4,4]]) %>
  <br>

  <%= f.label :date, "Date de Depart: " %>
  <%# f.collection_select :start_time, Flight.get_start_times, :start_time, :start_time_formatted %>
  <br>

  <%= f.date_select :date, start_year: Time.now.year,
  								 end_year: 8.years.from_now.year %>
  <br>

  <%= f.submit "Recherche" %>
<% end %>

app/views/flights/_select.html.erb
<% if params[:flight] %>
	<%= form_with(url: new_booking_path, method: 'get', local: true) do %>
	  <ul>
	  <% @flights.each do |flight| %>
	    <%= label_tag(:flight_id, "numero de vol: #{flight.id}") %>
	      <li>
      		Depart de: <%=  flight.from_airport.code %>
      		<br>
      		Arrive a: <%= flight.to_airport.code %>
      		<br>
      		Heure de depart: <%= flight.formatted_start_time %>
      		<br>
      		Duree: <%= flight.duration %>
      	    <%= radio_button_tag(:flight_id, flight.id) %>
          </li>
          <br>
	    <% end %>
	  </ul>
      <br>
      <%= hidden_field_tag(:num_tickets, params[:flight][:num_tickets]) %>
	  <br>
	  <%= submit_tag "Choisir"%>
	<% end %>

<% end %>

app/views/flights/index.html.erb
<%= render 'search' %>
<%= params.inspect %>
<br>
<%= render 'select' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "rechercher vols", flights_path %>
    <br>
    <%= yield %>
  </body>
</html>